### ISSUE TITLE
Crash when press ok button again (to stop recording)

### ISSUE THREAD

**Issue by anonym24** [chinmoyp/screenrecorder#7]
```
06-08 13:11:49.075 28561-28561/com.confusedbox.screenrecorder E/MediaRecorder: stop failed: -1007
06-08 13:11:49.076 28561-28561/com.confusedbox.screenrecorder D/AndroidRuntime: Shutting down VM
06-08 13:11:49.077 28561-28561/com.confusedbox.screenrecorder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.confusedbox.screenrecorder, PID: 28561
    java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at com.confusedbox.screenrecorder.MainActivity.onToggleScreenShare(MainActivity.java:94)
        at com.confusedbox.screenrecorder.MainActivity$1.onClick(MainActivity.java:56)
        at android.view.View.performClick(View.java:5215)
        at android.widget.CompoundButton.performClick(CompoundButton.java:122)
        at android.view.View$PerformClick.run(View.java:21193)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

**Comment by madushanjoel98** [comment]
Same
